# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20170501_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Profile'),
        ),
    ]
